package org.arcticquests.dev.world.item.tags;


import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.tag.TagKey;
import net.minecraft.util.Identifier;
import org.arcticquests.dev.MarvelSuperHeroes;

public class MarvelTags {

    public static class Blocks {
        public static final TagKey<Block> VIBRANIUM_ORES = make("vibranium_ores");
        public static final TagKey<Block> TITANIUM_ORES = make("titanium_ores");
        public static final TagKey<Block> PALLADIUM_ORES = make("palladium_ores");
        public static final TagKey<Block> HYDRA_AGENT_SPAWNABLE_ON = make("hydra_agent_spawnable_on");


        private static TagKey<Block> make(String name){
            return TagKey.of(RegistryKeys.BLOCK,Identifier.of(MarvelSuperHeroes.MOD_ID,name));
        }
    }

    public static class Items {
        public static final TagKey<Item> VIBRANIUM_ORES = create("vibranium_ores");
        public static final TagKey<Item> TITANIUM_ORES = create("titanium_ores");
        public static final TagKey<Item> PALLADIUM_ORES = create("palladium_ores");
        public static final TagKey<Item> SUIT_VARIANTS = create("suit_variants");
        public static final TagKey<Item> HIDES_OUTER_LAYER = create("hides_outer_layer");
        public static final TagKey<Item> INVISIBLE_WHEN_OPEN = create("invisible_when_open");
        public static final TagKey<Item> HAS_CAPE = create("has_cape");
        public static final TagKey<Item> SOUND_DAMPENING_BOOTS = create("sound_dampening_boots");
        public static final TagKey<Item> RENDER_HAND = create("render_hand");
        public static final TagKey<Item> POSE_HAND = create("pose_hand");
        public static final TagKey<Item> FLYING_ARMOR = create("flying_armor");
        public static final TagKey<Item> CAPTAIN_AMERICA_ARMOR = create("captain_america_armor");
        public static final TagKey<Item> CAPTAIN_AMERICA_HELMET = create("captain_america_helmet");
        public static final TagKey<Item> CAPTAIN_AMERICA_CHESTPLATE = create("captain_america_chestplate");
        public static final TagKey<Item> CAPTAIN_AMERICA_LEGGINGS = create("captain_america_leggings");
        public static final TagKey<Item> CAPTAIN_AMERICA_BOOTS = create("captain_america_boots");
        public static final TagKey<Item> BLACK_PANTHER_ARMOR = create("black_panther_armor");
        public static final TagKey<Item> BLACK_PANTHER_HELMET = create("black_panther_helmet");
        public static final TagKey<Item> BLACK_PANTHER_CHESTPLATE = create("black_panther_chestplate");
        public static final TagKey<Item> BLACK_PANTHER_LEGGINGS = create("black_panther_leggings");
        public static final TagKey<Item> BLACK_PANTHER_BOOTS = create("black_panther_boots");
        public static final TagKey<Item> KINETIC_BLACK_PANTHER_ARMOR = create("kinetic_black_panther_armor");
        public static final TagKey<Item> KINETIC_BLACK_PANTHER_HELMET = create("kinetic_black_panther_helmet");
        public static final TagKey<Item> KINETIC_BLACK_PANTHER_CHESTPLATE = create("kinetic_black_panther_chestplate");
        public static final TagKey<Item> KINETIC_BLACK_PANTHER_LEGGINGS = create("kinetic_black_panther_leggings");
        public static final TagKey<Item> KINETIC_BLACK_PANTHER_BOOTS = create("kinetic_black_panther_boots");
        public static final TagKey<Item> WOLVERINE_ARMOR = create("wolverine_armor");
        public static final TagKey<Item> WOLVERINE_HELMET = create("wolverine_helmet");
        public static final TagKey<Item> WOLVERINE_CHESTPLATE = create("wolverine_chestplate");
        public static final TagKey<Item> WOLVERINE_LEGGINGS = create("wolverine_leggings");
        public static final TagKey<Item> WOLVERINE_BOOTS = create("wolverine_boots");
        public static final TagKey<Item> CYCLOPS_ARMOR = create("cyclops_armor");
        public static final TagKey<Item> CYCLOPS_HELMET = create("cyclops_helmet");
        public static final TagKey<Item> CYCLOPS_CHESTPLATE = create("cyclops_chestplate");
        public static final TagKey<Item> CYCLOPS_LEGGINGS = create("cyclops_leggings");
        public static final TagKey<Item> CYCLOPS_BOOTS = create("cyclops_boots");
        public static final TagKey<Item> SPIDER_MAN_ARMOR = create("spider_man_armor");
        public static final TagKey<Item> SPIDER_MAN_HELMET = create("spider_man_helmet");
        public static final TagKey<Item> SPIDER_MAN_CHESTPLATE = create("spider_man_chestplate");
        public static final TagKey<Item> SPIDER_MAN_LEGGINGS = create("spider_man_leggings");
        public static final TagKey<Item> SPIDER_MAN_BOOTS = create("spider_man_boots");
        public static final TagKey<Item> ANT_MAN_ARMOR = create("ant_man_armor");
        public static final TagKey<Item> ANT_MAN_HELMET = create("ant_man_helmet");
        public static final TagKey<Item> ANT_MAN_CHESTPLATE = create("ant_man_chestplate");
        public static final TagKey<Item> ANT_MAN_LEGGINGS = create("ant_man_leggings");
        public static final TagKey<Item> ANT_MAN_BOOTS = create("ant_man_boots");
        public static final TagKey<Item> ANT_MAN_UPGRADED_ARMOR = create("ant_man_upgraded_armor");
        public static final TagKey<Item> ANT_MAN_UPGRADED_HELMET = create("ant_man_upgraded_helmet");
        public static final TagKey<Item> ANT_MAN_UPGRADED_CHESTPLATE = create("ant_man_upgraded_chestplate");
        public static final TagKey<Item> ANT_MAN_UPGRADED_LEGGINGS = create("ant_man_upgraded_leggings");
        public static final TagKey<Item> ANT_MAN_UPGRADED_BOOTS = create("ant_man_upgraded_boots");
        public static final TagKey<Item> WASP_ARMOR = create("wasp_armor");
        public static final TagKey<Item> WASP_HELMET = create("wasp_helmet");
        public static final TagKey<Item> WASP_CHESTPLATE = create("wasp_chestplate");
        public static final TagKey<Item> WASP_LEGGINGS = create("wasp_leggings");
        public static final TagKey<Item> WASP_BOOTS = create("wasp_boots");
        public static final TagKey<Item> THOR_ARMOR = create("thor_armor");
        public static final TagKey<Item> THOR_HELMET = create("thor_helmet");
        public static final TagKey<Item> THOR_CHESTPLATE = create("thor_chestplate");
        public static final TagKey<Item> THOR_LEGGINGS = create("thor_leggings");
        public static final TagKey<Item> THOR_BOOTS = create("thor_boots");
        public static final TagKey<Item> IRON_MAN_MARK_1_ARMOR = create("iron_man_mark_1_armor");
        public static final TagKey<Item> IRON_MAN_MARK_1_HELMET = create("iron_man_mark_1_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_1_CHESTPLATE = create("iron_man_mark_1_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_1_LEGGINGS = create("iron_man_mark_1_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_1_BOOTS = create("iron_man_mark_1_boots");
        public static final TagKey<Item> IRON_MAN_MARK_2_ARMOR = create("iron_man_mark_2_armor");
        public static final TagKey<Item> IRON_MAN_MARK_2_HELMET = create("iron_man_mark_2_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_2_CHESTPLATE = create("iron_man_mark_2_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_2_LEGGINGS = create("iron_man_mark_2_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_2_BOOTS = create("iron_man_mark_2_boots");
        public static final TagKey<Item> IRON_MAN_MARK_3_ARMOR = create("iron_man_mark_3_armor");
        public static final TagKey<Item> IRON_MAN_MARK_3_HELMET = create("iron_man_mark_3_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_3_CHESTPLATE = create("iron_man_mark_3_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_3_LEGGINGS = create("iron_man_mark_3_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_3_BOOTS = create("iron_man_mark_3_boots");
        public static final TagKey<Item> IRON_MAN_MARK_5_ARMOR = create("iron_man_mark_5_armor");
        public static final TagKey<Item> IRON_MAN_MARK_5_HELMET = create("iron_man_mark_5_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_5_CHESTPLATE = create("iron_man_mark_5_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_5_LEGGINGS = create("iron_man_mark_5_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_5_BOOTS = create("iron_man_mark_5_boots");
        public static final TagKey<Item> IRON_MAN_MARK_6_ARMOR = create("iron_man_mark_6_armor");
        public static final TagKey<Item> IRON_MAN_MARK_6_HELMET = create("iron_man_mark_6_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_6_CHESTPLATE = create("iron_man_mark_6_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_6_LEGGINGS = create("iron_man_mark_6_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_6_BOOTS = create("iron_man_mark_6_boots");
        public static final TagKey<Item> IRON_MAN_MARK_7_ARMOR = create("iron_man_mark_7_armor");
        public static final TagKey<Item> IRON_MAN_MARK_7_HELMET = create("iron_man_mark_7_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_7_CHESTPLATE = create("iron_man_mark_7_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_7_LEGGINGS = create("iron_man_mark_7_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_7_BOOTS = create("iron_man_mark_7_boots");
        public static final TagKey<Item> IRON_MAN_MARK_11_ARMOR = create("iron_man_mark_11_armor");
        public static final TagKey<Item> IRON_MAN_MARK_11_HELMET = create("iron_man_mark_11_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_11_CHESTPLATE = create("iron_man_mark_11_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_11_LEGGINGS = create("iron_man_mark_11_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_11_BOOTS = create("iron_man_mark_11_boots");
        public static final TagKey<Item> IRON_MAN_MARK_15_ARMOR = create("iron_man_mark_15_armor");
        public static final TagKey<Item> IRON_MAN_MARK_15_HELMET = create("iron_man_mark_15_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_15_CHESTPLATE = create("iron_man_mark_15_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_15_LEGGINGS = create("iron_man_mark_15_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_15_BOOTS = create("iron_man_mark_15_boots");
        public static final TagKey<Item> IRON_MAN_MARK_17_ARMOR = create("iron_man_mark_17_armor");
        public static final TagKey<Item> IRON_MAN_MARK_17_HELMET = create("iron_man_mark_17_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_17_CHESTPLATE = create("iron_man_mark_17_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_17_LEGGINGS = create("iron_man_mark_17_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_17_BOOTS = create("iron_man_mark_17_boots");
        public static final TagKey<Item> IRON_MAN_MARK_19_ARMOR = create("iron_man_mark_19_armor");
        public static final TagKey<Item> IRON_MAN_MARK_19_HELMET = create("iron_man_mark_19_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_19_CHESTPLATE = create("iron_man_mark_19_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_19_LEGGINGS = create("iron_man_mark_19_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_19_BOOTS = create("iron_man_mark_19_boots");
        public static final TagKey<Item> IRON_MAN_MARK_20_ARMOR = create("iron_man_mark_20_armor");
        public static final TagKey<Item> IRON_MAN_MARK_20_HELMET = create("iron_man_mark_20_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_20_CHESTPLATE = create("iron_man_mark_20_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_20_LEGGINGS = create("iron_man_mark_20_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_20_BOOTS = create("iron_man_mark_20_boots");
        public static final TagKey<Item> IRON_MAN_MARK_21_ARMOR = create("iron_man_mark_21_armor");
        public static final TagKey<Item> IRON_MAN_MARK_21_HELMET = create("iron_man_mark_21_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_21_CHESTPLATE = create("iron_man_mark_21_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_21_LEGGINGS = create("iron_man_mark_21_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_21_BOOTS = create("iron_man_mark_21_boots");
        public static final TagKey<Item> IRON_MAN_MARK_22_ARMOR = create("iron_man_mark_22_armor");
        public static final TagKey<Item> IRON_MAN_MARK_22_HELMET = create("iron_man_mark_22_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_22_CHESTPLATE = create("iron_man_mark_22_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_22_LEGGINGS = create("iron_man_mark_22_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_22_BOOTS = create("iron_man_mark_22_boots");
        public static final TagKey<Item> IRON_MAN_MARK_23_ARMOR = create("iron_man_mark_23_armor");
        public static final TagKey<Item> IRON_MAN_MARK_23_HELMET = create("iron_man_mark_23_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_23_CHESTPLATE = create("iron_man_mark_23_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_23_LEGGINGS = create("iron_man_mark_23_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_23_BOOTS = create("iron_man_mark_23_boots");
        public static final TagKey<Item> IRON_MAN_MARK_24_ARMOR = create("iron_man_mark_24_armor");
        public static final TagKey<Item> IRON_MAN_MARK_24_HELMET = create("iron_man_mark_24_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_24_CHESTPLATE = create("iron_man_mark_24_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_24_LEGGINGS = create("iron_man_mark_24_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_24_BOOTS = create("iron_man_mark_24_boots");
        public static final TagKey<Item> IRON_MAN_MARK_25_ARMOR = create("iron_man_mark_25_armor");
        public static final TagKey<Item> IRON_MAN_MARK_25_HELMET = create("iron_man_mark_25_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_25_CHESTPLATE = create("iron_man_mark_25_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_25_LEGGINGS = create("iron_man_mark_25_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_25_BOOTS = create("iron_man_mark_25_boots");
        public static final TagKey<Item> IRON_MAN_MARK_28_ARMOR = create("iron_man_mark_28_armor");
        public static final TagKey<Item> IRON_MAN_MARK_28_HELMET = create("iron_man_mark_28_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_28_CHESTPLATE = create("iron_man_mark_28_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_28_LEGGINGS = create("iron_man_mark_28_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_28_BOOTS = create("iron_man_mark_28_boots");
        public static final TagKey<Item> IRON_MAN_MARK_30_ARMOR = create("iron_man_mark_30_armor");
        public static final TagKey<Item> IRON_MAN_MARK_30_HELMET = create("iron_man_mark_30_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_30_CHESTPLATE = create("iron_man_mark_30_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_30_LEGGINGS = create("iron_man_mark_30_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_30_BOOTS = create("iron_man_mark_30_boots");
        public static final TagKey<Item> IRON_MAN_MARK_33_ARMOR = create("iron_man_mark_33_armor");
        public static final TagKey<Item> IRON_MAN_MARK_33_HELMET = create("iron_man_mark_33_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_33_CHESTPLATE = create("iron_man_mark_33_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_33_LEGGINGS = create("iron_man_mark_33_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_33_BOOTS = create("iron_man_mark_33_boots");
        public static final TagKey<Item> IRON_MAN_MARK_35_ARMOR = create("iron_man_mark_35_armor");
        public static final TagKey<Item> IRON_MAN_MARK_35_HELMET = create("iron_man_mark_35_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_35_CHESTPLATE = create("iron_man_mark_35_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_35_LEGGINGS = create("iron_man_mark_35_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_35_BOOTS = create("iron_man_mark_35_boots");
        public static final TagKey<Item> IRON_MAN_MARK_37_ARMOR = create("iron_man_mark_37_armor");
        public static final TagKey<Item> IRON_MAN_MARK_37_HELMET = create("iron_man_mark_37_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_37_CHESTPLATE = create("iron_man_mark_37_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_37_LEGGINGS = create("iron_man_mark_37_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_37_BOOTS = create("iron_man_mark_37_boots");
        public static final TagKey<Item> IRON_MAN_MARK_39_ARMOR = create("iron_man_mark_39_armor");
        public static final TagKey<Item> IRON_MAN_MARK_39_HELMET = create("iron_man_mark_39_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_39_CHESTPLATE = create("iron_man_mark_39_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_39_LEGGINGS = create("iron_man_mark_39_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_39_BOOTS = create("iron_man_mark_39_boots");
        public static final TagKey<Item> WAR_MACHINE_MARK_1_ARMOR = create("war_machine_mark_1_armor");
        public static final TagKey<Item> WAR_MACHINE_MARK_1_HELMET = create("war_machine_mark_1_helmet");
        public static final TagKey<Item> WAR_MACHINE_MARK_1_CHESTPLATE = create("war_machine_mark_1_chestplate");
        public static final TagKey<Item> WAR_MACHINE_MARK_1_LEGGINGS = create("war_machine_mark_1_leggings");
        public static final TagKey<Item> WAR_MACHINE_MARK_1_BOOTS = create("war_machine_mark_1_boots");
        public static final TagKey<Item> WAR_MACHINE_MARK_2_ARMOR = create("war_machine_mark_2_armor");
        public static final TagKey<Item> WAR_MACHINE_MARK_2_HELMET = create("war_machine_mark_2_helmet");
        public static final TagKey<Item> WAR_MACHINE_MARK_2_CHESTPLATE = create("war_machine_mark_2_chestplate");
        public static final TagKey<Item> WAR_MACHINE_MARK_2_LEGGINGS = create("war_machine_mark_2_leggings");
        public static final TagKey<Item> WAR_MACHINE_MARK_2_BOOTS = create("war_machine_mark_2_boots");
        public static final TagKey<Item> IRON_MAN_ARMOR = create("iron_man_armor");
        public static final TagKey<Item> IRON_MAN_HELMET = create("iron_man_helmet");
        public static final TagKey<Item> IRON_MAN_CHESTPLATE = create("iron_man_chestplate");
        public static final TagKey<Item> IRON_MAN_LEGGINGS = create("iron_man_leggings");
        public static final TagKey<Item> IRON_MAN_BOOTS = create("iron_man_boots");
        public static final TagKey<Item> WAR_MACHINE_ARMOR = create("war_machine_armor");
        public static final TagKey<Item> WAR_MACHINE_HELMET = create("war_machine_helmet");
        public static final TagKey<Item> WAR_MACHINE_CHESTPLATE = create("war_machine_chestplate");
        public static final TagKey<Item> WAR_MACHINE_LEGGINGS = create("war_machine_leggings");
        public static final TagKey<Item> WAR_MACHINE_BOOTS = create("war_machine_boots");
        public static final TagKey<Item> QUICKSILVER_ARMOR = create("quicksilver_armor");
        public static final TagKey<Item> QUICKSILVER_CHESTPLATE = create("quicksilver_chestplate");
        public static final TagKey<Item> QUICKSILVER_LEGGINGS = create("quicksilver_leggings");
        public static final TagKey<Item> QUICKSILVER_BOOTS = create("quicksilver_boots");
        public static final TagKey<Item> DEADPOOL_ARMOR = create("deadpool_armor");
        public static final TagKey<Item> DEADPOOL_HELMET = create("deadpool_helmet");
        public static final TagKey<Item> DEADPOOL_CHESTPLATE = create("deadpool_chestplate");
        public static final TagKey<Item> DEADPOOL_LEGGINGS = create("deadpool_leggings");
        public static final TagKey<Item> DEADPOOL_BOOTS = create("deadpool_boots");
        public static final TagKey<Item> CAPTAIN_MARVEL_ARMOR = create("captain_marvel_armor");
        public static final TagKey<Item> CAPTAIN_MARVEL_HELMET = create("captain_marvel_helmet");
        public static final TagKey<Item> CAPTAIN_MARVEL_CHESTPLATE = create("captain_marvel_chestplate");
        public static final TagKey<Item> CAPTAIN_MARVEL_LEGGINGS = create("captain_marvel_leggings");
        public static final TagKey<Item> CAPTAIN_MARVEL_BOOTS = create("captain_marvel_boots");
        public static final TagKey<Item> WINTER_SOLDIER_ARMOR = create("winter_soldier_armor");
        public static final TagKey<Item> WINTER_SOLDIER_CHESTPLATE = create("winter_soldier_chestplate");
        public static final TagKey<Item> WINTER_SOLDIER_LEGGINGS = create("winter_soldier_leggings");
        public static final TagKey<Item> WINTER_SOLDIER_BOOTS = create("winter_soldier_boots");

        private static TagKey<Item> create(String name) {
            return TagKey.of(RegistryKeys.ITEM, Identifier.of(MarvelSuperHeroes.MOD_ID, name));
        }
    }


}